//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        public int Id { get; set; }
        [DisplayName ("Product Name")]
        [Required (ErrorMessage ="Name is required")]
        public string name { get; set; }
        [DisplayName("Ice-Cream Type")]
        [Required(ErrorMessage = "Type is required")]
        public string type { get; set; }
        [DisplayName ("Image")]
        
        public string image { get; set; }
        [Required(ErrorMessage = "Price is required")]
        [DisplayName ("Price")]
        public int price { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
